# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database

- name: Instalar MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Asegurar que MySQL está en ejecución
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
